format_version: 10
pipelines:
  expense-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:GyXHWL0gRxZv2QFeUyYZVg==:FXeg4RTJXVaTeIq73zDqKw=="
      vault_token: "AES:TbWft/l7DJgukUaa2RYENQ==:Od+5ZJ8FyKsH1t/Eg9MCS3BmTeblwUCwlLx6gfDrZaU="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
              - exec: { command: bash, arguments: ["run.sh"] }

      - PROD:
          fetch_materials: true
          environment_variables: { env: prod, action: apply }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: bash , arguments: ["run.sh"] }
