format_version: 10
pipelines:
  expense-destroy:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:gByoteIR3R19U/x5M7a4oQ==:hzJuwlaTrq6Bna5gLndagg=="
      vault_token: "AES:ICgqyPiLyIRryboee7PT3A==:jMG7B5dSPNIgy1yyNWclxaVofEXrBU6ELtmkQir6NZo="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: destroy }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: bash , arguments: ["run.sh"] }



      - PROD:
          fetch_materials: true
          environment_variables: { env: prod, action: destroy }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash , arguments: ["run.sh"] }
