format_version: 10
pipelines:
  tools-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/tools-automation
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:GyXHWL0gRxZv2QFeUyYZVg==:FXeg4RTJXVaTeIq73zDqKw=="
      vault_token: "AES:TbWft/l7DJgukUaa2RYENQ==:Od+5ZJ8FyKsH1t/Eg9MCS3BmTeblwUCwlLx6gfDrZaU="
    stages:
      - create:
          fetch_materials: true
          environment_variables: { env: dev }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform , arguments: [ "init"] }
                - exec: { command: terraform , arguments: [ "apply", "-auto-approve"] }
