format_version: 10
pipelines:
  tools-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/poojachiru04/tools-automation
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:cq7xYqZCqw7+zxTJqHhbpg==:E7Ddrn3rEX2o58fsHNpGfQ=="
    stages:
      - create:
          fetch_materials: true
          environment_variables: { env: dev }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform , arguments: [ "init"] }
                - exec: { command: terraform , arguments: [ "apply", "-auto-approve"] }
