format_version: 10
pipelines:
  backend:
    group: App-deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD:  "AES:A+nXq97UPxer7CvBVvfQmQ==:AC+fXAbWrpsx+SG5sdFNkg=="
    environment_variables:
      component: backend
    template: ansible-app-deployment






