format_version: 10
pipelines:
  backend:
    group: App-deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -i
                - backend-dev.poodevops.online
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - -e
                - env=dev
                - -e
                - role_name=backend
                - expense.yml
                command: ansible-playbook

    - QA:
       fetch_materials: true
       approval:
         type: manual
       jobs:
         ansible:
           timeout: 0
           tasks:
           - exec:
               arguments:
               - -l
               command: ls
               run_if: passed

    - STAGE:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -l
                  command: ls
                  run_if: passed

    - PROD:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -i
                    - backend-prod.poodevops.online
                    - -e
                    - ansible_user=ec2-user
                    - -e
                    - ansible_password=DevOps321
                    - -e
                    - env=prod
                    - -e
                    - role_name=backend
                    - expense.yml
                  command: ansible-playbook






