format_version: 10
pipelines:
  frontend:
    group: App-deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:cq7xYqZCqw7+zxTJqHhbpg==:E7Ddrn3rEX2o58fsHNpGfQ=="
      vault_token: "AES:ajto9pfFdVcv7RBAD9papA==:p19FP42BOGtBx8rEx73OA0M6N4jfvk7lRu7ivnMQvH0="
    environment_variables:
      component: frontend
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
              - exec:
                  arguments:
                  - run.sh
                  command: bash

      - QA:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
              - exec:
                  arguments:
                  - -l
                  command: ls
                  run_if: passed

      - STAGE:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
              - exec:
                  arguments:
                  - -l
                  command: ls
                  run_if: passed

      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
              - exec:
                  arguments:
                  - run.sh
                  command: bash
                  run_if: passed