format_version: 10
pipelines:
  prometheus:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-92bef6d:
        git: https://github.com/poojachiru04/tools-automation
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:PqMlNf17hd57NXpU4jhXhA==:h9RwvNdy72k1uBBOXka1Mg=="
      vault_token: "AES:/K3wNdaf8m/tew1/DhgS1w==:9IH2/ufoTvQ7hD97Az6hyPpgvUzD/Tklsb4L5ZZelro="
    environment_variables:
      tool_name: prometheus
    stages:
      - create:
          fetch_materials: true
          approval: {type: manual}
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - setup-tool-service.sh
